services:
  # https://hub.docker.com/_/mysql
  # https://hub.docker.com/_/mariadb
  db:
    container_name: container-db
    image: mysql:8.0.33-oracle
    # image: mariadb:10.11.3-jammy
    environment:
      LANG: C.UTF-8
      TZ: UTC
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbname
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    networks:
      - default
    ports:
      - 3306:3306
    volumes:
      - ./docker/db/conf:/etc/mysql/conf.d:ro
      - ./docker/db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "mysql", "-u", "username", "-ppassword", "dbname"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    platform: linux/amd64

  # https://hub.docker.com/_/redis
  redis:
    container_name: container-redis
    image: redis:7.0.11-bullseye
    environment:
      LANG: C.UTF-8
      TZ: UTC
    networks:
      - default
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    # platform: linux/amd64

  # https://hub.docker.com/r/localstack/localstack
  localstack:
    container_name: container-localstack
    image: localstack/localstack:2.0.2
    environment:
      LANG: C.UTF-8
      TZ: UTC
      # https://docs.localstack.cloud/references/configuration/
      EAGER_SERVICE_LOADING: 1
      SERVICES: kms, s3
      # https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
      AWS_DEFAULT_REGION: ap-northeast-1
      AWS_DEFAULT_OUTPUT: json
    networks:
      - default
    ports:
      - 4566:4566
    volumes:
      - ./docker/localstack/init:/etc/localstack/init/ready.d
      - ./docker/localstack/keys:/app/keys
      - ./docker/localstack/data:/app/data
    healthcheck:
      test: ["CMD", "awslocal", "s3", "ls", "s3://test-bucket"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    # platform: linux/amd64

  # https://hub.docker.com/_/node
  node:
    container_name: container-node
    image: node:18.16.0-bullseye-slim
    depends_on:
      db:
        condition: service_healthy
      localstack:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      LANG: C.UTF-8
      TZ: UTC
      NODE_ENV: development
      # AWS config
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
      AWS_DEFAULT_REGION: ap-northeast-1
      AWS_REGION: ap-northeast-1
      # Application config
      AWS_ENDPOINT: "http://localstack:4566"
      DB_ENDPOINT: "mysql://username:password@db:3306/dbname"
      REDIS_ENDPOINT: "redis://redis:6379"
      S3_BUCKET_NAME: "test-bucket"
    networks:
      - default
    ports:
      - 3000:3000
    volumes:
      - .:/app
    working_dir: /app
    command: ["npm", "run", "dev"]
    # platform: linux/amd64
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 1024M

  # https://hub.docker.com/r/grafana/k6
  k6:
    container_name: container-k6
    image: grafana/k6:0.44.1
    environment:
      LANG: C.UTF-8
      TZ: UTC
      # BASE_URL: http://host.docker.internal:3000
      BASE_URL: http://node:3000
    networks:
      - default
    volumes:
      - ./docker/k6/script:/k6/script
    working_dir: /k6
    command: ["--version"]
    # platform: linux/amd64
    profiles:
      - test

networks:
  default:
    name: network-default
