services:
  # https://hub.docker.com/_/mysql
  # https://hub.docker.com/_/mariadb
  db:
    container_name: container-db
    image: mysql:8.0.33-oracle
    # image: mariadb:10.11.3-jammy
    environment:
      LANG: C.UTF-8
      TZ: UTC
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbname
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    networks:
      - default
    ports:
      - 3306:3306
    volumes:
      - ./docker/db/conf:/etc/mysql/conf.d:ro
      - ./docker/db/init:/docker-entrypoint-initdb.d:ro
    platform: linux/amd64

  # https://hub.docker.com/_/redis
  redis:
    container_name: container-redis
    image: redis:7.0.11-bullseye
    environment:
      LANG: C.UTF-8
      TZ: UTC
    networks:
      - default
    ports:
      - 6379:6379

  # https://hub.docker.com/r/localstack/localstack
  localstack:
    container_name: container-localstack
    image: localstack/localstack:2.0.2
    environment:
      LANG: C.UTF-8
      TZ: UTC
      # https://docs.localstack.cloud/references/configuration/
      EAGER_SERVICE_LOADING: 1
      SERVICES: kms, s3
      # https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
      AWS_DEFAULT_REGION: ap-northeast-1
      AWS_DEFAULT_OUTPUT: json
    networks:
      - default
    ports:
      - 4566:4566
    volumes:
      - ./docker/localstack/init:/etc/localstack/init/ready.d
      - ./docker/localstack/keys:/app/keys
      - ./docker/localstack/data:/app/data
    # platform: linux/amd64

  # https://hub.docker.com/r/grafana/k6
  k6:
    container_name: container-k6
    image: grafana/k6:0.44.1
    environment:
      LANG: C.UTF-8
      TZ: UTC
      BASE_URL: http://host.docker.internal:3000
    networks:
      - default
    volumes:
      - ./docker/k6/script:/k6/script
    working_dir: /k6
    command: ["--version"]
    # platform: linux/amd64

networks:
  default:
    name: network-default
